### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [3]:
import numpy as np

numeros_aleatorios = np.random.randint(1,51, size=10)
print(np.mean(numeros_aleatorios))
print(np.std(numeros_aleatorios))   

22.8
16.89852064531094


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [ ]:
import numpy as pd

num_ale = np.random.rand(10)
num_ale[num_ale <= 0.5] = np.sqrt(num_ale[num_ale <= 0.5])
print(num_ale)

[0.73159763 0.27033724 0.99744783 0.59410108 0.98974722 0.41509551
 0.67980251 0.40441843 0.24223516 0.92906277]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [ ]:
import numpy as np

matriz = np.random.rand(3, 3, 3)
valores = np.amax(matriz, axis=1)
print(valores)

[[0.9124474  0.92598438 0.6308114 ]
 [0.78205157 0.55626715 0.901723  ]
 [0.80950936 0.92049964 0.5170367 ]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [ ]:
import numpy as np 

matriz5 = np.random.rand(5,5)
media = np.mean(matriz5, axis=1)
matriz_media = matriz5 - media[:, np.newaxis]

print(matriz5)
print(media)
print(matriz_media)

[[0.0851951  0.4736367  0.48878172 0.8800374  0.39974915]
 [0.42517636 0.05406235 0.3829879  0.87126455 0.6745591 ]
 [0.23539796 0.91411984 0.29068143 0.54050361 0.42805836]
 [0.87162226 0.66386747 0.9995579  0.2847554  0.48324861]
 [0.60956554 0.34410616 0.81251174 0.16554078 0.64069385]]
[0.46548001 0.48161005 0.48175224 0.66061033 0.51448361]
[[-0.38028492  0.00815669  0.02330171  0.41455738 -0.06573086]
 [-0.05643369 -0.4275477  -0.09862215  0.3896545   0.19294905]
 [-0.24635428  0.4323676  -0.19107081  0.05875137 -0.05369388]
 [ 0.21101193  0.00325714  0.33894758 -0.37585493 -0.17736172]
 [ 0.09508193 -0.17037746  0.29802812 -0.34894283  0.12621024]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [5]:
import numpy as np

matriz = np.random.rand(4, 4)

diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])

print(matriz)
print(diag_principal)
print(diag_secundaria)
print(media_diag)
print(std_diag)

[[0.59404188 0.53564931 0.02219969 0.75178366]
 [0.16072753 0.41725919 0.04880711 0.51361134]
 [0.97647812 0.88098082 0.87824056 0.19453817]
 [0.10311899 0.47499511 0.96874105 0.26345378]]
[0.59404188 0.41725919 0.87824056 0.26345378]
[0.75178366 0.04880711 0.88098082 0.10311899]
0.49221074742873794
0.31302067166859937
